apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: donaemeka/restauranty-auth:latest
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: secret
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: mongodb_uri
        livenessProbe:
          httpGet:
            path: /api/auth
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
  - port: 3001
    targetPort: 3001
  spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true    # Prevent container from running as root user
        runAsUser: 1000       # Run as user ID 1000 (non-privileged user)
      containers:
      - name: [service-name]
        securityContext:
          allowPrivilegeEscalation: false  # Prevent privilege escalation attacks
          capabilities:
            drop:
            - ALL             # Remove all Linux capabilities for security
